name: Build and Push Docker Image

# Déclencher le workflow sur les commits à la branche 'main'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Set up Docker Buildx (nécessaire pour builder et pousser l'image)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASWD}}

      # Étape 4 : Construire et pousser l'image Docker sur Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Emplacement de ton Dockerfile
          push: true
          tags: talognon/myfastapi-app:latest

      # Étape 5 : Déconnexion de Docker Hub
     # - name: Log out from Docker Hub
       # run: docker logout
